# Generated by Django 4.2.4 on 2023-08-05 11:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("airport", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="city",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="country",
            options={"ordering": ["name"], "verbose_name_plural": "countries"},
        ),
    ]
