# Generated by Django 4.2.4 on 2023-08-05 13:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("airport", "0003_alter_city_options_alter_country_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="airplane",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="airplanetype",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="crew",
            options={"ordering": ["last_name"]},
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["created_at"]},
        ),
    ]
