# Generated by Django 4.2.4 on 2023-08-05 15:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("airport", "0005_rename_city_airport_closest_big_city_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="airplane",
            unique_together={("name", "airplane_type")},
        ),
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together={("row", "seat")},
        ),
    ]
