version: '3'

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    command: >
      sh -c "python3 manage.py wait_for_db &&
             python3 manage.py migrate &&
             python3 manage.py loaddata fixtures/user_data &&
             python3 manage.py loaddata fixtures/airport_data &&
             python3 manage.py collectstatic --noinput &&
             python3 manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    depends_on:
      - db
    image: diashiro/airport-api-service:airport-api-service

  db:
    image: postgres:14-alpine
    ports:
      - "5433:5432"
    env_file:
      - .env
